"""
Preprocess HyperKvasir labeled-images dataset cho YOLO detection.

Luồng:
  1. Giải nén hyper-kvasir-labeled-images.zip
  2. Lọc các class liên quan đến nội soi dạ dày (upper GI + polyps)
  3. Gán nhãn YOLO: full-image bbox (không có bbox annotation gốc)
  4. Chia train/val 80/20
  5. Xuất dataset.yaml

Classes:
  0: normal     — pylorus, retroflex-stomach, z-line
  1: lesion     — barretts, barretts-short-segment, esophagitis-a,
                  esophagitis-b-d, polyps
"""

import os
import shutil
import zipfile
import random
from pathlib import Path

# ─── Cấu hình ────────────────────────────────────────────────────────────────

ZIP_PATH   = Path("data/raw/hyper-kvasir-labeled-images.zip")
OUTPUT_DIR = Path("data/hyperkvasir_yolo")

TRAIN_RATIO = 0.8
RANDOM_SEED = 42

# Class mapping: folder_name → class_id
CLASS_MAP = {
    # Normal anatomy (upper GI)
    "pylorus":             0,
    "retroflex-stomach":   0,
    "z-line":              0,
    # Lesions / pathological (upper GI)
    "barretts":            1,
    "barretts-short-segment": 1,
    "esophagitis-a":       1,
    "esophagitis-b-d":     1,
    # Polyps (lower GI — dùng được cho gastroscopy)
    "polyps":              1,
}

CLASS_NAMES = ["normal", "lesion"]


# ─── Helpers ─────────────────────────────────────────────────────────────────

def make_yolo_label(class_id: int) -> str:
    """Full-image bounding box: center (0.5, 0.5), size (1.0, 1.0)."""
    return f"{class_id} 0.5 0.5 1.0 1.0\n"


def copy_with_label(src: Path, img_dst: Path, lbl_dst: Path, class_id: int):
    shutil.copy2(src, img_dst)
    lbl_dst.write_text(make_yolo_label(class_id))


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    random.seed(RANDOM_SEED)

    # 1. Giải nén vào thư mục tạm
    extract_dir = Path("data/raw/hyperkvasir_extracted")
    if not extract_dir.exists():
        print(f"Đang giải nén {ZIP_PATH} ...")
        with zipfile.ZipFile(ZIP_PATH) as zf:
            zf.extractall(extract_dir)
        print("Giải nén xong.")
    else:
        print(f"Đã giải nén trước đó tại {extract_dir}, bỏ qua.")

    # 2. Thu thập tất cả ảnh theo class
    collected: dict[int, list[Path]] = {0: [], 1: []}

    for folder_name, class_id in CLASS_MAP.items():
        # Tìm folder trong cây thư mục đã giải nén
        matches = list(extract_dir.rglob(folder_name))
        if not matches:
            print(f"  [!] Không tìm thấy folder: {folder_name}")
            continue
        folder = matches[0]
        images = sorted(folder.glob("*.jpg")) + sorted(folder.glob("*.png"))
        collected[class_id].extend(images)
        print(f"  {len(images):5d}  {folder_name}  → class {class_id}")

    total = sum(len(v) for v in collected.values())
    print(f"\nTổng: {total} ảnh  (normal={len(collected[0])}, lesion={len(collected[1])})")

    # 3. Tạo cấu trúc YOLO output
    for split in ("train", "val"):
        (OUTPUT_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
        (OUTPUT_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)

    # 4. Chia và copy
    stats = {"train": {0: 0, 1: 0}, "val": {0: 0, 1: 0}}

    for class_id, paths in collected.items():
        random.shuffle(paths)
        n_train = int(len(paths) * TRAIN_RATIO)
        splits = {"train": paths[:n_train], "val": paths[n_train:]}

        for split, split_paths in splits.items():
            for src in split_paths:
                stem = f"{src.parent.name}_{src.stem}"
                img_dst = OUTPUT_DIR / "images" / split / f"{stem}{src.suffix}"
                lbl_dst = OUTPUT_DIR / "labels" / split / f"{stem}.txt"
                copy_with_label(src, img_dst, lbl_dst, class_id)
                stats[split][class_id] += 1

    print(f"\nTrain: normal={stats['train'][0]}, lesion={stats['train'][1]}")
    print(f"Val:   normal={stats['val'][0]},  lesion={stats['val'][1]}")

    # 5. Xuất dataset.yaml
    abs_output = OUTPUT_DIR.resolve()
    yaml_content = f"""# HyperKvasir — Gastroscopy subset
# Generated by scripts/preprocess_hyperkvasir.py

path: {abs_output}
train: images/train
val:   images/val

nc: {len(CLASS_NAMES)}
names: {CLASS_NAMES}
"""
    yaml_path = OUTPUT_DIR / "dataset.yaml"
    yaml_path.write_text(yaml_content)
    print(f"\nDataset YAML: {yaml_path}")
    print("Xong!")


if __name__ == "__main__":
    main()